#pragma once

#include <QtCore/qglobal.h>

#ifndef BUILD_STATIC
# if defined(COMMUNICATIONINTERFACE_LIB)
#  define COMMUNICATIONINTERFACE_EXPORT Q_DECL_EXPORT
# else
#  define COMMUNICATIONINTERFACE_EXPORT Q_DECL_IMPORT
# endif
#else
# define COMMUNICATIONINTERFACE_EXPORT
#endif
